version: '3.8'

services:
  node_backend:
    container_name: node_cei
    image: node_cei:0.0.1
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - EXTERNAL_PORT=3000
      - PGDATABASE=cei_db
      - PGUSER=rathi
      - PGPASSWORD=1234
      - PGHOST=node_db
    depends_on:
      - node_db
  node_db:
    container_name: node_db
    image: "postgres:12"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=rathi
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=cei_db
    volumes:
      - nps_data:/var/lib/postgresql/data

volumes:
  nps_data: {}
