#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: server
##  namespace: dev
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: server
#  template:
#    metadata:
#      labels:
#        app: server
#    spec:
#      containers:
#        - image: docker.io/rathidockerrepo/node-image:latest
#          name: server
#          ports:
#            - containerPort: 4000
#          imagePullPolicy: Always
#          envFrom:
#            - configMapRef:
#                name: server

apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
          - name: server
            image: node-cei:0.0.1
            imagePullPolicy: Never
            env:
              - name: POSTGRES_HOST
                value: postgres://postgres:12345@postgres:5432/users-postgres-k8s
              - name: CLIENT
                value: http://192.168.64.5:30000/
              - name: PORT
                value: "8000"
