apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi



#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: mysql-persistent-storage
#  labels:
#    app: wordpress
#spec:
#  accessModes:
#    - ReadWriteMany
#  resources:
#    requests:
#      storage: 1Gi
#  selector:
#    matchLabels:
#      tier: "mysql"
