apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "postgres-config"
  namespace: "default"
  labels:
    app: "postgres"
data:
  POSTGRES_DB: "users-postgres-k8s"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "12345"
